apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developer-cluster-access
rules:
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs: ["*"]
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs: ["*"]
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  - namespaces
  verbs: ["get", "list"]
